CREATE OR REPLACE VIEW DOSTUPNA_VOZIDLA_VIEW AS
SELECT
    v.ID_VOZIDLA,
    tv.NAZEV AS TYP_VOZIDLA,
    tv.ZNACKA AS ZNACKA,
    NVL(l.CISLO_LINKY, 0) AS JEZDI_NA_LINCE
FROM
    ST67028.VOZIDLA v
        JOIN ST67028.TYPY_VOZIDEL tv ON v.ID_TYP_VOZIDLA = tv.ID_TYP_VOZIDLA
        LEFT JOIN ST67028.JIZDY j ON v.ID_VOZIDLA = j.ID_VOZIDLA
        LEFT JOIN ST67028.LINKY l ON j.ID_LINKY = l.ID_LINKY;
