create PROCEDURE CheckUserExists (
    p_username IN VARCHAR2,
    p_exists OUT NUMBER
) AS
BEGIN
    SELECT COUNT(*)
    INTO p_exists
    FROM ST67028.UZIVATELE
    WHERE UZIVATELSKE_JMENO = p_username;

    IF p_exists > 0 THEN
        p_exists := 1;
    ELSE
        p_exists := 0;
    END IF;
END CheckUserExists;
/

CREATE OR REPLACE VIEW UZIVATEL_VIEW AS
SELECT
    u.ID_UZIVATELE,
    u.UZIVATELSKE_JMENO,
    u.HESLO,
    u.JMENO,
    u.PRIJMENI,
    u.CAS_ZALOZENI,
    u.DATUM_NAROZENI,
    tu.NAZEV AS TYP_UZIVATELE,
    a.ID_ADRESY,
    a.MESTO,
    a.ULICE,
    a.CISLO_POPISNE,
    f.ID_FOTO,
    f.JMENO_SOUBORU AS FOTO_JMENO_SOUBORU,
    f.DATA AS FOTO_DATA,
    f.DATUM_PRIDANI AS FOTO_DATUM_PRIDANI
FROM ST67028.UZIVATELE u
         LEFT JOIN ST67028.TYPY_UZIVATELE tu ON u.ID_TYP_UZIVATELE = tu.ID_TYP_UZIVATELE
         LEFT JOIN ST67028.ADRESY a ON u.ID_ADRESY = a.ID_ADRESY
         LEFT JOIN ST67028.FOTO f ON u.ID_UZIVATELE = f.ID_UZIVATELE;
/
