CREATE OR REPLACE VIEW DB_OBJEKTY_VIEW AS
SELECT
    OBJECT_NAME AS NAZEV_OBJEKTU,
    OBJECT_TYPE AS TYP_OBJEKTU,
    STATUS AS STATUS_OBJEKTU,
    CREATED AS DATUM_VYTVORENI,
    LAST_DDL_TIME AS POSLEDNI_MODIFIKACE
FROM
    USER_OBJECTS
ORDER BY
    OBJECT_TYPE, OBJECT_NAME;