CREATE OR REPLACE VIEW UZIVATEL_VIEW AS
SELECT
    u.ID_UZIVATELE,
    u.UZIVATELSKE_JMENO,
    u.HESLO,
    u.JMENO,
    u.PRIJMENI,
    u.CAS_ZALOZENI,
    u.DATUM_NAROZENI,
    tu.NAZEV AS TYP_UZIVATELE,
    a.ID_ADRESY,
    a.MESTO,
    a.ULICE,
    a.CISLO_POPISNE,
    f_user.ID_FOTO AS ID_FOTO,
    f_user.JMENO_SOUBORU AS FOTO_JMENO_SOUBORU,
    f_user.DATA AS FOTO_DATA,
    f_user.DATUM_PRIDANI AS FOTO_DATUM_PRIDANI
FROM ST67028.UZIVATELE u
         LEFT JOIN ST67028.TYPY_UZIVATELE tu ON u.ID_TYP_UZIVATELE = tu.ID_TYP_UZIVATELE
         LEFT JOIN ST67028.ADRESY a ON u.ID_ADRESY = a.ID_ADRESY
         LEFT JOIN (
    SELECT
        ID_UZIVATELE,
        ID_FOTO,
        JMENO_SOUBORU,
        DATA,
        DATUM_PRIDANI
    FROM ST67028.FOTO
    WHERE ID_UZIVATELE IS NOT NULL
) f_user ON u.ID_UZIVATELE = f_user.ID_UZIVATELE;
/


CREATE OR REPLACE VIEW ST67028.ZASTAVKY_LINKY_VIEW AS
SELECT
    l.ID_LINKY,
    l.CISLO_LINKY,
    z.ID_ZASTAVKY,
    z.JMENO AS JMENO_ZASTAVKY,
    zs.ODJEZD,
    zs.ITERACE,
    zs.SMER
FROM
    ST67028.LINKY l
        JOIN
    ST67028.ZASTAVENI zs ON l.ID_LINKY = zs.ID_LINKY
        JOIN
    ST67028.ZASTAVKY z ON zs.ID_ZASTAVKY = z.ID_ZASTAVKY
/


CREATE OR REPLACE VIEW PLATBY_VIEW AS
SELECT
    p.ID_PLATBY,
    p.CAS_PLATBY,
    p.VYSE_PLATBY,
    p.TYP_PLATBY,
    CASE
        WHEN p.TYP_PLATBY = 0 THEN 'Platba kartou'
        WHEN p.TYP_PLATBY = 1 THEN 'Platba převodem'
        ELSE 'Neznámý typ platby'
        END AS TYP_PLATBY_TEXT,
    z.ID_ZAKAZNIKA,
    u.JMENO || ' ' || u.PRIJMENI AS JMENO_ZAKAZNIKA,
    CASE
        WHEN p.TYP_PLATBY = 0 THEN pk.CISLO_KARTY
        WHEN p.TYP_PLATBY = 1 THEN pp.CISLO_UCTU
        ELSE NULL
        END AS DETAIL_PLATBY
FROM
    ST67028.PLATBY p
        JOIN ST67028.ZAKAZNICI z ON p.ID_ZAKAZNIKA = z.ID_ZAKAZNIKA
        JOIN ST67028.UZIVATELE u ON z.ID_UZIVATELE = u.ID_UZIVATELE
        LEFT JOIN ST67028.PLATBY_KARTOU pk ON p.ID_PLATBY = pk.ID_PLATBY
        LEFT JOIN ST67028.PLATBY_PREVODEM pp ON p.ID_PLATBY = pp.ID_PLATBY
/


CREATE OR REPLACE VIEW ST67028.ZASTAVKY_LINKY_VIEW AS
SELECT
    l.ID_LINKY,
    l.CISLO_LINKY,
    z.ID_ZASTAVKY,
    z.JMENO AS JMENO_ZASTAVKY,
    zs.ODJEZD,
    zs.ITERACE,
    zs.SMER
FROM
    ST67028.LINKY l
        JOIN
    ST67028.ZASTAVENI zs ON l.ID_LINKY = zs.ID_LINKY
        JOIN
    ST67028.ZASTAVKY z ON zs.ID_ZASTAVKY = z.ID_ZASTAVKY
/


CREATE OR REPLACE VIEW DOSTUPNA_VOZIDLA_VIEW AS
SELECT
    v.ID_VOZIDLA,
    tv.NAZEV AS TYP_VOZIDLA,
    v.ZNACKA AS ZNACKA,
    NVL(l.CISLO_LINKY, 0) AS JEZDI_NA_LINCE
FROM
    ST67028.VOZIDLA v
        JOIN ST67028.TYPY_VOZIDEL tv ON v.ID_TYP_VOZIDLA = tv.ID_TYP_VOZIDLA
        LEFT JOIN ST67028.JIZDY j ON v.ID_VOZIDLA = j.ID_VOZIDLA
        LEFT JOIN ST67028.LINKY l ON j.ID_LINKY = l.ID_LINKY
/


CREATE OR REPLACE VIEW ST67028.ZAMESTNANCI_VIEW AS
SELECT
    z.ID_ZAMESTNANCE,
    u.JMENO AS JMENO,
    u.PRIJMENI AS PRIJMENI,
    u.UZIVATELSKE_JMENO AS UZIVATELSKE_JMENO,
    z.PLAT,
    z.PLATNOST_UVAZKU_DO,
    n.JMENO AS JMENO_NADRIZENEHO,
    n.PRIJMENI AS PRIJMENI_NADRIZENEHO
FROM
    ST67028.ZAMESTNANCI z
        JOIN ST67028.UZIVATELE u ON z.ID_UZIVATELE = u.ID_UZIVATELE
        LEFT JOIN ST67028.ZAMESTNANCI zn ON z.ID_NADRIZENEHO = zn.ID_ZAMESTNANCE
        LEFT JOIN ST67028.UZIVATELE n ON zn.ID_UZIVATELE = n.ID_UZIVATELE;
/       